version: '3.8'

services:

#  db:
#    container_name: phonebook_postgres
#    image: postgres:16.0-alpine
#    env_file:
#      - .env
#    volumes:
#      - ./db_backup:/var/lib/postgresql/data
  django:
    container_name: phonebook_django
    tty: true
    stdin_open: true
    build: .
    volumes:
      - .:/app
    command: >
      sh -c "python /app/manage.py collectstatic --noinput &&
             python /app/manage.py makemigrations &&
             python /app/manage.py migrate &&
             gunicorn phonebook.wsgi --threads 4 --timeout 240 --bind 0.0.0.0:8005  --reload --workers 3 --chdir /app/"
    restart: always
    expose:
      - 8005
    ports:
      - "8005:8005"
    env_file:
      - .env


